/*
 * GENERATED by :tools:asset-region-editor — DO NOT EDIT.
 * Source of truth: tools/asset-regions/asset_regions.json
 * Re-run with `./gradlew :tools:asset-region-editor:run`, edit regions,
 * then click "Generar catálogos Kotlin" in the tool.
 */
@file:Suppress("unused", "ObjectPropertyName")
package com.google.ai.edge.gallery.customtasks.stocatstic.ui.assets

object PathCatalogGen {
  val ENTRIES: List<GalleryEntry> = listOf(
    GalleryEntry(id = "stones1", label = "Piedra", assetPath = "stocatstic/Tilesets/Nature_Tileset.png", col = 4, row = 11, colSpan = 1, rowSpan = 1),
    GalleryEntry(id = "flowers", label = "Pétalos", assetPath = "stocatstic/Tilesets/Tileset_Floor_Detail.png", col = 3, row = 1, colSpan = 1, rowSpan = 1),
    GalleryEntry(id = "dirt", label = "Tierra", assetPath = "stocatstic/Tilesets/Tileset_Floor_Detail.png", col = 1, row = 5, colSpan = 1, rowSpan = 1),
    GalleryEntry(id = "sand", label = "Arena", assetPath = "stocatstic/Tilesets/Tileset_Floor_Detail.png", col = 2, row = 5, colSpan = 1, rowSpan = 1),
    GalleryEntry(id = "leaves", label = "Hojas", assetPath = "stocatstic/Tilesets/Tileset_Floor_Detail.png", col = 7, row = 5, colSpan = 1, rowSpan = 1),
    GalleryEntry(id = "stones", label = "Piedras", assetPath = "stocatstic/Tilesets/Tileset_Floor_Detail.png", col = 8, row = 5, colSpan = 1, rowSpan = 1),
    GalleryEntry(id = "crop_row", label = "Surco", assetPath = "stocatstic/Tilesets/Tileset_Floor_Detail.png", col = 3, row = 6, colSpan = 1, rowSpan = 1),
  )
}

object RootCatalogGen {
  val ENTRIES: List<GalleryEntry> = listOf(
    GalleryEntry(id = "haystack", label = "Paja", assetPath = "stocatstic/Tilesets/Barn_Tileset.png", col = 27, row = 2, colSpan = 1, rowSpan = 1),
    GalleryEntry(id = "mailbox", label = "Buzón", assetPath = "stocatstic/Tilesets/Exterior_Tileset.png", col = 4, row = 2, colSpan = 1, rowSpan = 1),
    GalleryEntry(id = "well", label = "Pozo", assetPath = "stocatstic/Tilesets/Exterior_Tileset.png", col = 9, row = 5, colSpan = 2, rowSpan = 2),
    GalleryEntry(id = "sign", label = "Cartel", assetPath = "stocatstic/Tilesets/Exterior_Tileset.png", col = 9, row = 7, colSpan = 1, rowSpan = 1),
    GalleryEntry(id = "lantern", label = "Farol", assetPath = "stocatstic/Tilesets/Exterior_Tileset.png", col = 16, row = 9, colSpan = 1, rowSpan = 2),
    GalleryEntry(id = "barrel", label = "Barril", assetPath = "stocatstic/Tilesets/Exterior_Tileset.png", col = 21, row = 9, colSpan = 1, rowSpan = 2),
    GalleryEntry(id = "pot", label = "Maceta", assetPath = "stocatstic/Tilesets/Exterior_Tileset.png", col = 6, row = 10, colSpan = 1, rowSpan = 2),
    GalleryEntry(id = "rock", label = "Roca", assetPath = "stocatstic/Tilesets/Nature_Tileset.png", col = 22, row = 3, colSpan = 1, rowSpan = 1),
  )
}

object TaskSpriteCatalogGen {
  val ENTRIES: List<GalleryEntry> = listOf(
    GalleryEntry(id = "camp_00", label = "Hoguera", assetPath = "stocatstic/Object Animation/Campfire.png", col = 6, row = 1, colSpan = 1, rowSpan = 1, assetType = AssetType.SOLID),
    GalleryEntry(id = "hs_04", label = "Cofre", assetPath = "stocatstic/Object Animation/Chest.png", col = 0, row = 7, colSpan = 1, rowSpan = 1, assetType = AssetType.NORMAL),
    GalleryEntry(id = "bn_00", label = "Heno", assetPath = "stocatstic/Tilesets/Barn_Tileset.png", col = 28, row = 2, colSpan = 2, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "sheeps", label = "Obejas", assetPath = "stocatstic/Tilesets/Barn_Tileset.png", col = 23, row = 5, colSpan = 1, rowSpan = 1, assetType = AssetType.NORMAL),
    GalleryEntry(id = "cows", label = "Vacas", assetPath = "stocatstic/Tilesets/Barn_Tileset.png", col = 24, row = 5, colSpan = 1, rowSpan = 1, assetType = AssetType.NORMAL),
    GalleryEntry(id = "chikens", label = "Pollos", assetPath = "stocatstic/Tilesets/Barn_Tileset.png", col = 25, row = 5, colSpan = 1, rowSpan = 1),
    GalleryEntry(id = "egg", label = "Huevo", assetPath = "stocatstic/Tilesets/Barn_Tileset.png", col = 28, row = 5, colSpan = 1, rowSpan = 1),
    GalleryEntry(id = "goats", label = "Goat", assetPath = "stocatstic/Tilesets/Barn_Tileset.png", col = 23, row = 6, colSpan = 1, rowSpan = 1, assetType = AssetType.NORMAL),
    GalleryEntry(id = "ducks", label = "Patos", assetPath = "stocatstic/Tilesets/Barn_Tileset.png", col = 24, row = 6, colSpan = 1, rowSpan = 1, assetType = AssetType.NORMAL),
    GalleryEntry(id = "crop_00", label = "Brote", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 1, row = 6, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "crop_01", label = "Planta", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 22, row = 6, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "crop_07", label = "Maíz", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 13, row = 7, colSpan = 1, rowSpan = 2, assetType = AssetType.PLANT),
    GalleryEntry(id = "crop_02", label = "Flor roja", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 16, row = 7, colSpan = 1, rowSpan = 2, assetType = AssetType.PLANT),
    GalleryEntry(id = "crop_05", label = "Flor violeta", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 6, row = 8, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "crop_14", label = "Pepino", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 24, row = 8, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "crop_09", label = "Calabaza", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 3, row = 9, colSpan = 1, rowSpan = 2, assetType = AssetType.PLANT),
    GalleryEntry(id = "crop_12", label = "Cebolla", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 6, row = 9, colSpan = 1, rowSpan = 2, assetType = AssetType.PLANT),
    GalleryEntry(id = "crop_08", label = "Tomate", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 9, row = 9, colSpan = 1, rowSpan = 2, assetType = AssetType.PLANT),
    GalleryEntry(id = "crop_10", label = "Zanahoria", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 11, row = 9, colSpan = 1, rowSpan = 2, assetType = AssetType.PLANT),
    GalleryEntry(id = "crop_06", label = "Trigo", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 13, row = 9, colSpan = 1, rowSpan = 2, assetType = AssetType.PLANT),
    GalleryEntry(id = "crop_11", label = "Patata", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 15, row = 9, colSpan = 1, rowSpan = 2, assetType = AssetType.PLANT),
    GalleryEntry(id = "crop_03", label = "Flor amarilla", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 17, row = 9, colSpan = 1, rowSpan = 2, assetType = AssetType.PLANT),
    GalleryEntry(id = "crop_04", label = "Flor azul", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 19, row = 9, colSpan = 1, rowSpan = 2, assetType = AssetType.PLANT),
    GalleryEntry(id = "crop_13", label = "Berenjena", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 25, row = 9, colSpan = 1, rowSpan = 2, assetType = AssetType.PLANT),
    GalleryEntry(id = "post1", label = "Tomate", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 1, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post2", label = "Patata", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 2, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post3", label = "Trigo", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 3, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post4", label = "Zanahoria", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 4, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post5", label = "Tomate", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 5, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post6", label = "Zanahoria", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 6, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post7", label = "Patata", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 7, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post8", label = "Zanahoria", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 8, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post9", label = "Maíz", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 9, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post10", label = "Tomate", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 10, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post11", label = "Trigo", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 11, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post12", label = "Berenjena", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 12, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post13", label = "Trigo", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 13, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post14", label = "Trigo", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 14, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post15", label = "Cebolla", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 15, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post16", label = "Berenjena", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 16, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post17", label = "Berenjena", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 17, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post18", label = "Berenjena", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 18, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post19", label = "Maíz", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 19, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post20", label = "Zanahoria", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 20, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post21", label = "Zanahoria", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 21, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post22", label = "Berenjena", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 22, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post23", label = "Trigo", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 23, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post24", label = "Zanahoria", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 24, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post25", label = "Berenjena", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 25, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post26", label = "Berenjena", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 26, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "post27", label = "Berenjena", assetPath = "stocatstic/Tilesets/Crops_Tileset.png", col = 27, row = 12, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "ext_05", label = "Buzón", assetPath = "stocatstic/Tilesets/Exterior_Tileset.png", col = 2, row = 1, colSpan = 1, rowSpan = 2, assetType = AssetType.NORMAL),
    GalleryEntry(id = "ext_04", label = "Pozo", assetPath = "stocatstic/Tilesets/Exterior_Tileset.png", col = 13, row = 5, colSpan = 2, rowSpan = 2, assetType = AssetType.NORMAL),
    GalleryEntry(id = "ext_00", label = "Farol", assetPath = "stocatstic/Tilesets/Exterior_Tileset.png", col = 14, row = 7, colSpan = 1, rowSpan = 2, assetType = AssetType.NORMAL),
    GalleryEntry(id = "hs_05", label = "Lámpara", assetPath = "stocatstic/Tilesets/Exterior_Tileset.png", col = 16, row = 7, colSpan = 1, rowSpan = 2, assetType = AssetType.NORMAL),
    GalleryEntry(id = "ext_01", label = "Cartel", assetPath = "stocatstic/Tilesets/Exterior_Tileset.png", col = 9, row = 8, colSpan = 1, rowSpan = 1, assetType = AssetType.NORMAL),
    GalleryEntry(id = "bn_02", label = "Saco", assetPath = "stocatstic/Tilesets/Exterior_Tileset.png", col = 20, row = 8, colSpan = 1, rowSpan = 1, assetType = AssetType.NORMAL),
    GalleryEntry(id = "ext_03", label = "Caja", assetPath = "stocatstic/Tilesets/Exterior_Tileset.png", col = 21, row = 8, colSpan = 1, rowSpan = 1, assetType = AssetType.NORMAL),
    GalleryEntry(id = "ext_02", label = "Barril", assetPath = "stocatstic/Tilesets/Exterior_Tileset.png", col = 20, row = 9, colSpan = 1, rowSpan = 2, assetType = AssetType.PLANT),
    GalleryEntry(id = "bn_01", label = "Bidón", assetPath = "stocatstic/Tilesets/Exterior_Tileset.png", col = 22, row = 10, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
    GalleryEntry(id = "nat_03", label = "Matojo", assetPath = "stocatstic/Tilesets/Nature_Tileset.png", col = 3, row = 1, colSpan = 1, rowSpan = 1, assetType = AssetType.SOLID),
    GalleryEntry(id = "nat_00", label = "Arbusto", assetPath = "stocatstic/Tilesets/Nature_Tileset.png", col = 4, row = 1, colSpan = 1, rowSpan = 1, assetType = AssetType.SOLID),
    GalleryEntry(id = "nat_01", label = "Arbusto 2", assetPath = "stocatstic/Tilesets/Nature_Tileset.png", col = 5, row = 1, colSpan = 1, rowSpan = 1, assetType = AssetType.SOLID),
    GalleryEntry(id = "nat_02", label = "Mata", assetPath = "stocatstic/Tilesets/Nature_Tileset.png", col = 6, row = 1, colSpan = 1, rowSpan = 1, assetType = AssetType.SOLID),
    GalleryEntry(id = "nat_06", label = "Rocas", assetPath = "stocatstic/Tilesets/Nature_Tileset.png", col = 13, row = 1, colSpan = 2, rowSpan = 2, assetType = AssetType.SOLID),
    GalleryEntry(id = "nat_05", label = "Tocón", assetPath = "stocatstic/Tilesets/Nature_Tileset.png", col = 1, row = 6, colSpan = 2, rowSpan = 2, assetType = AssetType.SOLID),
    GalleryEntry(id = "structur1", label = "Troncos+", assetPath = "stocatstic/Tilesets/Nature_Tileset.png", col = 3, row = 7, colSpan = 2, rowSpan = 1),
    GalleryEntry(id = "structure", label = "Troncos", assetPath = "stocatstic/Tilesets/Nature_Tileset.png", col = 3, row = 7, colSpan = 1, rowSpan = 1, assetType = AssetType.SOLID),
    GalleryEntry(id = "nat_04", label = "Tronco", assetPath = "stocatstic/Tilesets/Nature_Tileset.png", col = 6, row = 8, colSpan = 2, rowSpan = 1, assetType = AssetType.SOLID),
    GalleryEntry(id = "crop_15", label = "Setas", assetPath = "stocatstic/Tilesets/Nature_Tileset.png", col = 12, row = 11, colSpan = 1, rowSpan = 1, assetType = AssetType.SOLID),
    GalleryEntry(id = "nat_07", label = "Flor silvestre", assetPath = "stocatstic/Tilesets/Tileset_Floor_Detail.png", col = 2, row = 2, colSpan = 1, rowSpan = 1, assetType = AssetType.PLANT),
  )
}

object CharacterCatalogGen {
  val ALL: List<CharacterEntry> = listOf(
    CharacterEntry(id = "bunny", label = "Conejo", idle = "stocatstic/Characters/BUNNY/IDLE/Bunny_Idle.png", run = "stocatstic/Characters/BUNNY/RUN/Bunny_Run.png", hoe = "stocatstic/Characters/BUNNY/HOE/Bunny_Hoe.png", scythe = "stocatstic/Characters/BUNNY/SCYTHE/Bunny_Scythe.png", water = "stocatstic/Characters/BUNNY/WATERING CAN/Bunny_WateringCan.png", sword = "stocatstic/Characters/BUNNY/SWORD/Bunny_Sword.png", hurt = "stocatstic/Characters/BUNNY/HURT/Bunny_Hurt.png"),
    CharacterEntry(id = "duck", label = "Pato", idle = "stocatstic/Characters/DUCK/IDLE/Duck_Idle.png", run = "stocatstic/Characters/DUCK/RUN/Duck_Run.png", hoe = "stocatstic/Characters/DUCK/HOE/Duck_Hoe.png", scythe = "stocatstic/Characters/DUCK/SCYTHE/Duck_Scythe.png", water = "stocatstic/Characters/DUCK/WATERING CAN/Duck_WateringCan.png", sword = "stocatstic/Characters/DUCK/SWORD/Sword_Duck.png", hurt = "stocatstic/Characters/DUCK/HURT/Duck_Hurt.png"),
    CharacterEntry(id = "lion", label = "León", idle = "stocatstic/Characters/LION/IDLE/Idle lion.png", run = "stocatstic/Characters/LION/RUN/Run lion.png", hoe = "stocatstic/Characters/LION/HOE/Hoe lion.png", scythe = "stocatstic/Characters/LION/SCYTHE/Scythe lion.png", water = "stocatstic/Characters/LION/WATERING CAN/Watering can lion.png", sword = "stocatstic/Characters/LION/SWORD/Sword lion.png", hurt = "stocatstic/Characters/LION/HURT/Hurt lion.png"),
    CharacterEntry(id = "monkey", label = "Mono", idle = "stocatstic/Characters/MONKEY/IDLE/Idle monkey.png", run = "stocatstic/Characters/MONKEY/RUN/Run monkey.png", hoe = "stocatstic/Characters/MONKEY/HOE/Monkey_Hoe.png", scythe = "stocatstic/Characters/MONKEY/SCYTHE/Scythe monkey.png", water = "stocatstic/Characters/MONKEY/WATERING CAN/Monkey_WateringCan.png", sword = "stocatstic/Characters/MONKEY/SWORD/Sword monkey.png", hurt = "stocatstic/Characters/MONKEY/HURT/Hurt monkey.png"),
  )
}

