/*
 * Copyright 2026 SIRGPrice
 *
 * This file is part of Blue Edge: https://github.com/SIRGPrice/Blue-Edge
 *
 * Licensed under the Blue Edge Custom License 1.0.
 * You may not use this file except in compliance with that license.
 * GitHub may host, cache, display, and facilitate collaboration on this file
 * as required by the GitHub Terms of Service.
 * See the repository root: BLUE_EDGE_CUSTOM_LICENSE.md
 */
package com.blueedge.assettool.codegen

import com.blueedge.assettool.io.RepoPaths
import com.blueedge.assettool.model.AssetRegionsFile
import com.blueedge.assettool.model.Category
import com.blueedge.assettool.model.CharacterSlot
import com.blueedge.assettool.model.RegionEntry

/**
 * Emits `AssetCatalogs.generated.kt` next to the manual `AssetCatalogs.kt`.
 * The manual file keeps the `data class` definitions and the `*Catalog` objects
 * that expose DEFAULT / byId helpers; the generated file provides the raw
 * `ENTRIES` / `ALL` lists via `*CatalogGen` objects.
 */
object KotlinCatalogGenerator {

  fun generate(file: AssetRegionsFile): String {
    val sb = StringBuilder()
    sb.appendLine("""
      /*
       * GENERATED by :tools:asset-region-editor — DO NOT EDIT.
       * Source of truth: tools/asset-regions/asset_regions.json
       * Re-run with `./gradlew :tools:asset-region-editor:run`, edit regions,
       * then click "Generar catálogos Kotlin" in the tool.
       */
      @file:Suppress("unused", "ObjectPropertyName")
      package com.google.ai.edge.gallery.customtasks.stocatstic.ui.assets
    """.trimIndent())
    sb.appendLine()

    sb.appendObjectEntries(
      name = "PathCatalogGen",
      regions = file.regions.filter { it.category == Category.PATH },
      includeAssetType = false,
    )
    sb.appendLine()

    sb.appendObjectEntries(
      name = "RootCatalogGen",
      regions = file.regions.filter { it.category == Category.ROOT },
      includeAssetType = false,
    )
    sb.appendLine()

    sb.appendObjectEntries(
      name = "TaskSpriteCatalogGen",
      regions = file.regions.filter { it.category == Category.TASK_SPRITE },
      includeAssetType = true,
    )
    sb.appendLine()

    sb.appendCharactersObject(file.regions.filter { it.category == Category.CHARACTER })
    sb.appendLine()

    return sb.toString()
  }

  fun writeToFile(file: AssetRegionsFile): java.io.File {
    val out = RepoPaths.generatedKt
    out.parentFile.mkdirs()
    out.writeText(generate(file), Charsets.UTF_8)
    return out
  }

  // ---- helpers ---------------------------------------------------------------------------------

  private fun StringBuilder.appendObjectEntries(
    name: String,
    regions: List<RegionEntry>,
    includeAssetType: Boolean,
  ) {
    appendLine("object $name {")
    appendLine("  val ENTRIES: List<GalleryEntry> = listOf(")
    for (r in regions) {
      val typeArg = if (includeAssetType) {
        r.assetType?.let { ", assetType = AssetType.${it.name}" } ?: ""
      } else ""
      appendLine(
        "    GalleryEntry(" +
          "id = ${r.id.klit()}, " +
          "label = ${r.label.klit()}, " +
          "assetPath = ${r.assetPath.klit()}, " +
          "col = ${r.col}, row = ${r.row}, " +
          "colSpan = ${r.colSpan}, rowSpan = ${r.rowSpan}$typeArg),"
      )
    }
    appendLine("  )")
    appendLine("}")
  }

  private fun StringBuilder.appendCharactersObject(regions: List<RegionEntry>) {
    // Group by characterId, fall back to id if null.
    val byChar = regions
      .groupBy { it.characterId ?: it.id }
      .toSortedMap()

    appendLine("object CharacterCatalogGen {")
    appendLine("  val ALL: List<CharacterEntry> = listOf(")
    for ((charId, strips) in byChar) {
      fun pathFor(slot: CharacterSlot): String? =
        strips.firstOrNull { it.characterSlot == slot }?.assetPath
      val idle = pathFor(CharacterSlot.IDLE) ?: ""
      val run = pathFor(CharacterSlot.RUN) ?: ""
      val hoe = pathFor(CharacterSlot.HOE) ?: ""
      val scythe = pathFor(CharacterSlot.SCYTHE) ?: ""
      val water = pathFor(CharacterSlot.WATER) ?: ""
      val sword = pathFor(CharacterSlot.SWORD) ?: ""
      val hurt = pathFor(CharacterSlot.HURT) ?: ""
      val label = strips.firstOrNull()?.label ?: charId
      appendLine(
        "    CharacterEntry(" +
          "id = ${charId.klit()}, label = ${label.klit()}, " +
          "idle = ${idle.klit()}, run = ${run.klit()}, hoe = ${hoe.klit()}, " +
          "scythe = ${scythe.klit()}, water = ${water.klit()}, " +
          "sword = ${sword.klit()}, hurt = ${hurt.klit()}),"
      )
    }
    appendLine("  )")
    appendLine("}")
  }

  /** Kotlin string literal escaping. */
  private fun String.klit(): String {
    val esc = buildString(length + 2) {
      append('"')
      for (c in this@klit) when (c) {
        '\\' -> append("\\\\")
        '"' -> append("\\\"")
        '\n' -> append("\\n")
        '\r' -> append("\\r")
        '\t' -> append("\\t")
        '$' -> append("\\$")
        else -> append(c)
      }
      append('"')
    }
    return esc
  }
}

